db:
  dialect: postgres
  schema: public
  host: localhost
  port: 5432
  user: doctor_vet
  password: doctor_vet
  name: doctor_vet
  debug: true
  max_idle_conns: 25
  max_open_conns: 25
  conn_max_lifetime: 5m
  ssl: false

public:
  host: "localhost"
  port: 3000
  idle_timeout: 5m
  read_timeout: 10s
  write_timeout: 10s
private:
  host: "localhost"
  port: 3001
  idle_timeout: 5m
  read_timeout: 10s
  write_timeout: 10s
admin:
  host: "localhost"
  port: 3002
  idle_timeout: 5m
  read_timeout: 10s
  write_timeout: 10s
  
keycloak:
  url: "http://localhost:8080/auth"
  realm: "doctor_vet"
  client_id: "dovtor_vet_client"
  secret: "4DpiMsSSm03VdV7VwFUMg5F0gYz2NDPu"
  rsa256: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2Ohoqxk7yeUcSy+pdUWMwOur9KgqwKQ6+sDHdFaL5zF0YjMvvr+Kkb+IOPZ8yXERI5kRZrZxKU+RD8G+I9WBjLqzfNZ7sFYJAOC6MX48/cRYxaiFnHxv/2S/C/0KxNS1WyyTjVMKijqaSHXdgeGPfR/4PaPlV7e8Y2KWZb+cdZ46NuWAijNi9BB/ugLq3+v1wgSUHgx2d/sdcEqKlYCuTH3ajwYfe6BuIjkuRZzq28A9LRaGu0ovPFQbvvmjhNUn4EgkN5eEZ45riXmfMez8nW0EOrHppQR1jc7FiiZf/lrFUWB0mwBJt2g3pEgsQ5iNTTJv8Vk1MJDREQ+jgJvuMQIDAQAB"
