definitions:
  doctor-vet-patients_transport_models.Patient:
    properties:
      address:
        description: Адрес проживания, обязательно
        type: string
      age:
        description: Возраст животного в годах, >= 0
        minimum: 0
        type: number
      animal:
        description: Животное, обязательно
        type: string
      breed:
        description: Порода животного, обязательно
        type: string
      fio:
        description: ФИО пациента, обязательно
        type: string
      gender:
        description: Пол животного, "male" или "female"
        enum:
        - мужской
        - женский
        type: string
      id:
        example: 1
        type: integer
      isNeutered:
        description: Информация о стерилизации
        type: boolean
      name:
        description: Имя животного, обязательно
        type: string
      phone:
        description: Телефон в формате E.164, обязательно
        type: string
    required:
    - address
    - animal
    - breed
    - fio
    - gender
    - id
    - name
    - phone
    type: object
  doctor-vet-patients_transport_models.Prescription:
    properties:
      amount:
        type: string
      course:
        type: string
      createdAt:
        type: string
      dose:
        type: string
      id:
        type: integer
      preparation:
        type: string
      treatmentId:
        type: integer
      updatedAt:
        type: string
    required:
    - amount
    - course
    - createdAt
    - dose
    - id
    - preparation
    - treatmentId
    - updatedAt
    type: object
  doctor-vet-patients_transport_models.Treatment:
    properties:
      beginAt:
        type: string
      comment:
        type: string
      createdAt:
        type: string
      doctorId:
        type: string
      endAt:
        type: string
      id:
        type: integer
      isActive:
        type: integer
      patient:
        allOf:
        - $ref: '#/definitions/doctor-vet-patients_transport_models.Patient'
        description: инфа пациента
      patientId:
        type: integer
      status:
        type: string
      temperature:
        description: Температура тела животного, >= 0
        minimum: 0
        type: number
      updatedAt:
        type: string
      weight:
        description: Вес животного в кг, >= 0
        minimum: 0
        type: number
    required:
    - beginAt
    - comment
    - createdAt
    - doctorId
    - endAt
    - id
    - isActive
    - patientId
    - status
    - updatedAt
    type: object
  models.Response:
    properties:
      code:
        type: integer
      description:
        type: string
      message:
        type: string
    type: object
  models.TreatmentDetail:
    properties:
      beginAt:
        type: string
      comment:
        type: string
      createdAt:
        type: string
      doctorId:
        type: string
      endAt:
        type: string
      id:
        type: integer
      isActive:
        type: integer
      patient:
        allOf:
        - $ref: '#/definitions/doctor-vet-patients_transport_models.Patient'
        description: инфа пациента
      patientId:
        type: integer
      prescriptions:
        description: список лечения
        items:
          $ref: '#/definitions/doctor-vet-patients_transport_models.Prescription'
        type: array
      status:
        type: string
      temperature:
        description: Температура тела животного, >= 0
        minimum: 0
        type: number
      updatedAt:
        type: string
      weight:
        description: Вес животного в кг, >= 0
        minimum: 0
        type: number
    required:
    - beginAt
    - comment
    - createdAt
    - doctorId
    - endAt
    - id
    - isActive
    - patientId
    - status
    - updatedAt
    type: object
info:
  contact: {}
  description: API для работы с пациентами и их данными
  termsOfService: http://swagger.io.terms/
  version: "1.0"
paths:
  /patient:
    post:
      consumes:
      - application/json
      description: Создать нового пациента
      operationId: create_patient
      parameters:
      - description: Запрос
        in: body
        name: Form
        required: true
        schema:
          $ref: '#/definitions/doctor-vet-patients_transport_models.Patient'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Ошибка запроса
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/models.Response'
      summary: Создать нового пациента
      tags:
      - patients
  /treatment/{id}:
    get:
      consumes:
      - application/json
      description: Возвращает детали  лечения
      operationId: get_treatment
      parameters:
      - description: ID treatment
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Детали лечения
          schema:
            items:
              $ref: '#/definitions/models.TreatmentDetail'
            type: array
        "400":
          description: Ошибка запроса
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/models.Response'
      summary: Получить детали лечения
      tags:
      - treatment
  /treatments:
    get:
      consumes:
      - application/json
      description: Возвращает список всех лечений
      operationId: get_treatments
      parameters:
      - description: Фильтр по ФИО
        in: query
        name: fio
        type: string
      - description: Фильтр по кличке
        in: query
        name: name
        type: string
      - description: Фильтр по статусу
        in: query
        name: status
        type: string
      - description: Лимит записей (по умолчанию 10)
        in: query
        name: limit
        type: integer
      - description: Смещение для пагинации (по умолчанию 0)
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Список лечений
          schema:
            items:
              $ref: '#/definitions/doctor-vet-patients_transport_models.Treatment'
            type: array
        "400":
          description: Ошибка запроса
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/models.Response'
      summary: Получить список лечений
      tags:
      - treatment
schemes:
- http
swagger: "2.0"
